-- 기존 테이블 삭제
DROP TABLE TBL_USER CASCADE CONSTRAINTS;
DROP TABLE TBL_USER_DOCUMENT CASCADE CONSTRAINTS;
DROP TABLE TBL_PICK_ROOM CASCADE CONSTRAINTS;
DROP TABLE TBL_ROOM CASCADE CONSTRAINTS;
DROP TABLE TBL_ROOM_FILE CASCADE CONSTRAINTS;
DROP TABLE TBL_ROOM_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE TBL_OFFICE CASCADE CONSTRAINTS;
DROP TABLE TBL_OFFICE_DOCUMENT CASCADE CONSTRAINTS;
DROP TABLE TBL_TRANSACTION_LIST CASCADE CONSTRAINTS;
DROP TABLE TBL_REVIEW CASCADE CONSTRAINTS;
DROP TABLE TBL_REPORT CASCADE CONSTRAINTS;
DROP TABLE TBL_REPORT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE TBL_FREE_BOARD CASCADE CONSTRAINTS;
DROP TABLE TBL_FREE_BOARD_FILE CASCADE CONSTRAINTS;
DROP TABLE TBL_REPLY CASCADE CONSTRAINTS;
DROP TABLE TBL_PAYMENT_LIST CASCADE CONSTRAINTS;
DROP TABLE TBL_MEMBERSHIP CASCADE CONSTRAINTS;
DROP TABLE TBL_NOTICE CASCADE CONSTRAINTS;
DROP TABLE TBL_CONNECT_STATISTIC CASCADE CONSTRAINTS;
DROP TABLE TBL_ROOM_STATISTIC CASCADE CONSTRAINTS;
DROP TABLE TBL_INFO_BOARD CASCADE CONSTRAINTS;
DROP TABLE TBL_INFO_BOARD_FILE CASCADE CONSTRAINTS;
DROP TABLE TBL_INFO_CATEGORY CASCADE CONSTRAINTS;

-- 기존 시퀀스 삭제
DROP SEQUENCE SEQ_USER_NO;
DROP SEQUENCE SEQ_ROOM_NO;
DROP SEQUENCE SEQ_FREE_POST_NO;
DROP SEQUENCE SEQ_OFFICE_NO;
DROP SEQUENCE SEQ_REVIEW_NO;
DROP SEQUENCE SEQ_REPORT_NO;
DROP SEQUENCE SEQ_INFO_POST_NO;
DROP SEQUENCE SEQ_MEMBERSHIP_NO;
DROP SEQUENCE SEQ_REPLY_NO;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER_NO;
CREATE SEQUENCE SEQ_ROOM_NO;
CREATE SEQUENCE SEQ_FREE_POST_NO;
CREATE SEQUENCE SEQ_OFFICE_NO;
CREATE SEQUENCE SEQ_REVIEW_NO;
CREATE SEQUENCE SEQ_REPORT_NO;
CREATE SEQUENCE SEQ_INFO_POST_NO;
CREATE SEQUENCE SEQ_MEMBERSHIP_NO;
CREATE SEQUENCE SEQ_REPLY_NO;


-- 테이블 생성
----------------------------------------------------------------- 회원관련

-- TBL_USER 테이블 생성
CREATE TABLE TBL_USER (
  USER_NO NUMBER CONSTRAINT PK_U_USER_NO PRIMARY KEY,
  USER_ID VARCHAR2(20) CONSTRAINT NN_U_USER_ID NOT NULL,
  USER_PWD VARCHAR2(255) CONSTRAINT NN_U_USER_PWD NOT NULL,
  NICKNAME	VARCHAR2(255) CONSTRAINT NN_U_NICKNAME NOT NULL,
  EMAIL	VARCHAR2(50) CONSTRAINT NN_U_EMAIL NOT NULL,
  PHONE VARCHAR2(20) CONSTRAINT NN_U_PHONE NOT NULL,
  USER_ROLE VARCHAR2(15) DEFAULT 'MEMBER' CONSTRAINT NN_U_USER_ROLE NOT NULL,
  APPLY_DATE DATE,
  APPROVAL_YN CHAR(1),
  ENROLL_DATE DATE,
  USER_STATUS VARCHAR2(2),
  CONSTRAINT UK_U_USER_ID UNIQUE(USER_ID),
  CONSTRAINT UK_U_EMAIL UNIQUE(EMAIL),
  CONSTRAINT UK_U_PHONE UNIQUE(PHONE),
  CONSTRAINT CK_U_USER_ROLE CHECK(USER_ROLE IN ('MEMBER', 'OFFICE', 'ADMIN')),
  CONSTRAINT CK_U_APPROVAL_YN CHECK(APPROVAL_YN IN ('Y', 'N'))
);

COMMENT ON COLUMN TBL_USER.USER_NO IS '회원번호';
COMMENT ON COLUMN TBL_USER.USER_ID IS '아이디';
COMMENT ON COLUMN TBL_USER.USER_PWD IS '비밀번호';
COMMENT ON COLUMN TBL_USER.NICKNAME IS '닉네임';
COMMENT ON COLUMN TBL_USER.EMAIL IS '이메일';
COMMENT ON COLUMN TBL_USER.PHONE IS '전화번호';
COMMENT ON COLUMN TBL_USER.USER_ROLE IS '회원구분';
COMMENT ON COLUMN TBL_USER.APPLY_DATE IS '가입신청일';
COMMENT ON COLUMN TBL_USER.APPROVAL_YN IS '승인여부';
COMMENT ON COLUMN TBL_USER.ENROLL_DATE IS '회원등록일';
COMMENT ON COLUMN TBL_USER.USER_STATUS IS '회원상태';

-- 관리자 계정 추가 (!! 비밀번호 암호화 필요 !!)
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, USER_ROLE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'admin', '$2a$10$7NqnZ0pUQh2RDLDkcEmubOSWB2DSewpDNs7q7xwxgZHHvMgZGJ.rW', '관리자', 'admin@sabangpalbang.com', '01048884888', 'ADMIN', 'Y');


-- 회원 샘플 추가 (!! 비밀번호 암호화 필요 !!)
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'yoo', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '유코딩', 'yoo@sabang.com', '01011111111', TO_DATE('21/03/08', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'min', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '민코딩', 'min@sabang.com', '01022222222', TO_DATE('21/03/08', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'kim', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '김코딩', 'kim@sabang.com', '01033333333', TO_DATE('21/03/14', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'lee', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '이코딩', 'lee@sabang.com', '01044444444', TO_DATE('21/03/19', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'yoon', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '윤코딩', 'yoon@sabang.com', '01055555555', TO_DATE('21/03/21', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'park', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '박코딩', 'park@sabang.com', '01066666666', TO_DATE('21/03/27', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'choi', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '최코딩', 'choi@sabang.com', '01077777777', TO_DATE('21/03/29', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'jin', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '진코딩', 'jin@sabang.com', '01088888888', TO_DATE('21/04/03', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'han', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '한코딩', 'han@sabang.com', '01099999999', TO_DATE('21/04/06', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'jeong', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '정코딩', 'jeong@sabang.com', '01011112222', TO_DATE('21/04/08', 'RR/MM/DD'), 'Y');

-- 중개사 회원 샘플 추가 (!! 비밀번호 암호화 필요 !!)
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, USER_ROLE, APPLY_DATE, APPROVAL_YN, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'office1', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '나문휘', 'nmh@sabang.com', '01012341234', 'OFFICE', TO_DATE('21/03/08', 'RR/MM/DD'), 'Y', TO_DATE('21/03/10', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, USER_ROLE, APPLY_DATE, APPROVAL_YN, ENROLL_DATE, USER_STATUS)
VALUES (SEQ_USER_NO.NEXTVAL, 'office2', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '이숭재', 'lsj@sabang.com', '01056785678', 'OFFICE', TO_DATE('21/03/24', 'RR/MM/DD'), 'Y', TO_DATE('21/03/25', 'RR/MM/DD'), 'Y');
INSERT INTO TBL_USER (USER_NO, USER_ID, USER_PWD, NICKNAME, EMAIL, PHONE, USER_ROLE, APPLY_DATE)
VALUES (SEQ_USER_NO.NEXTVAL, 'office3', '$2a$10$y7xBHP6.2CyixOLcWL.sXeeO02vQPRYmtzYV7Kv.X7Xt7CkIEcqMO', '공지철', 'kjc@sabang.com', '01012345678', 'OFFICE', TO_DATE('21/04/05', 'RR/MM/DD'));

COMMIT;

-------------------------------------------------------------------- 매물관련


-- 매물_카테고리
CREATE TABLE TBL_ROOM_CATEGORY(
  CATEGORY_NO NUMBER CONSTRAINT PK_CATEGORY_NO PRIMARY KEY,
  CATEGORY_NAME VARCHAR2(50) CONSTRAINT NN_CATEGORY_NAME NOT NULL
);
COMMENT ON COLUMN TBL_ROOM_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN TBL_ROOM_CATEGORY.CATEGORY_NAME IS '카테고리이름';

INSERT INTO TBL_ROOM_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (1, '원룸');


---------- 중개사무소 ----------
CREATE TABLE TBL_OFFICE (
  OFFICE_NO	NUMBER CONSTRAINT PK_OFFICE_NO PRIMARY KEY,
  OFFICE_NAME VARCHAR2(50) CONSTRAINT NN_OFFICE_NAME NOT NULL,
  OFFICE_ADDR VARCHAR2(100) CONSTRAINT NN_OFFICE_ADDR NOT NULL,
  OFFICE_PHONE	VARCHAR2(20) CONSTRAINT NN_OFFICE_PHONE NOT NULL,
  BUSINESS_NO NUMBER  CONSTRAINT NN_BUSINESS_NO NOT NULL,
  OFFICE_RATING NUMBER,
  USER_NO NUMBER CONSTRAINT NN_OF_USER_NO NOT NULL,
  CONSTRAINT UK_OFFICE_PHONE UNIQUE (OFFICE_PHONE),
  CONSTRAINT UK_BUSINESS_NO UNIQUE (BUSINESS_NO),
  CONSTRAINT FK_OF_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT UK_OF_USER_NO UNIQUE (USER_NO)
);

COMMENT ON COLUMN TBL_OFFICE.OFFICE_NO IS '사무소번호';
COMMENT ON COLUMN TBL_OFFICE.OFFICE_NAME IS '사무소이름';
COMMENT ON COLUMN TBL_OFFICE.OFFICE_ADDR IS '사무소주소';
COMMENT ON COLUMN TBL_OFFICE.OFFICE_PHONE IS '사무소전화번호';
COMMENT ON COLUMN TBL_OFFICE.BUSINESS_NO IS '사업자등록번호';
COMMENT ON COLUMN TBL_OFFICE.OFFICE_RATING IS '평점';
COMMENT ON COLUMN TBL_OFFICE.USER_NO IS '대표중개사';

INSERT INTO TBL_OFFICE (OFFICE_NO, OFFICE_NAME, OFFICE_ADDR, OFFICE_PHONE, BUSINESS_NO, OFFICE_RATING, USER_NO)
VALUES (SEQ_OFFICE_NO.NEXTVAL, '402 공인중개사', '관악구 국회단지 29-11', '02-1234-5678', 9102034212346, 4, 12);
INSERT INTO TBL_OFFICE (OFFICE_NO, OFFICE_NAME, OFFICE_ADDR, OFFICE_PHONE, BUSINESS_NO, OFFICE_RATING, USER_NO)
VALUES (SEQ_OFFICE_NO.NEXTVAL, '짱조아 공인중개사', '관악구 국회단지 29-22', '02-1234-5012', 9102034234539, 5, 13);

--------- 가입서류 ---------
CREATE TABLE TBL_OFFICE_DOCUMENT (
  FILE_NO NUMBER CONSTRAINT NN_OD_FILE_NO NOT NULL,
  OFFICE_NO NUMBER CONSTRAINT NN_OD_OFFICE_NO NOT NULL,
  ORIGIN_NAME VARCHAR2(50) CONSTRAINT NN_OD_ORIGIN_NAME NOT NULL,
  SAVE_NAME VARCHAR2(50) CONSTRAINT NN_OD_SAVE_NAME NOT NULL,
  EXTENSION VARCHAR2(50) CONSTRAINT NN_OD_EXTENSION NOT NULL,
  CONTENT VARCHAR2(50),
  SAVE_PATH VARCHAR2(100) CONSTRAINT NN_OD_SAVE_PATH NOT NULL,
  CONSTRAINT PK_FILE_NO_AND_OFFICE_NO PRIMARY KEY (FILE_NO, OFFICE_NO),
  CONSTRAINT FK_OD_OFFICE_NO FOREIGN KEY (OFFICE_NO) REFERENCES TBL_OFFICE (OFFICE_NO)
);

COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.OFFICE_NO IS '사무소번호';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.EXTENSION IS '파일확장자';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.CONTENT IS '파일내용';
COMMENT ON COLUMN TBL_OFFICE_DOCUMENT.SAVE_PATH IS '저장경로';


-- 매물_기본정보
CREATE TABLE TBL_ROOM(
  ROOM_NO NUMBER CONSTRAINT PK_RM_ROOM_NO PRIMARY KEY,
  ROOM_PRICE NUMBER CONSTRAINT NN_RM_ROOM_PRICE NOT NULL,
  ROOM_STATUS CHAR(1) DEFAULT 'Y',
  EXCLUSIVE_AREA NUMBER CONSTRAINT NN_RM_EXCLUSIVE_AREA NOT NULL,
  ADDRESS VARCHAR2(255) CONSTRAINT NN_RM_ADDRESS NOT NULL,
  CREATE_DATE DATE DEFAULT SYSDATE,
  CATEGORY_NO NUMBER CONSTRAINT NN_RM_CATEGORY_NO NOT NULL,
  OFFICE_NO NUMBER CONSTRAINT NN_RM_OFFICE_NO NOT NULL,
  ROOM_FLOOR VARCHAR2(50) CONSTRAINT NN_RM_ROOM_FLOOR NOT NULL,
  DIRECTION VARCHAR2(50) CONSTRAINT NN_RM_DIRECTION NOT NULL,
  MONTH_COST NUMBER CONSTRAINT NN_RM_MONTH_COST NOT NULL,
  COST_INCLUDE VARCHAR2(100),
  CONSTRUCTION_DATE DATE CONSTRAINT NN_RM_CONSTRUCTION_DATE NOT NULL,
  AVAILABLE_DATE VARCHAR2(50) CONSTRAINT NN_RM_AVAILABLE_DATE NOT NULL,
  ROOM_EXPLANATION VARCHAR2(4000) CONSTRAINT NN_RM_ROOM_EXPLANATION NOT NULL,
  TRANSPORTATION_INFO VARCHAR2(255) CONSTRAINT NN_RM_TRANSPORTATION_INFO NOT NULL,
  WASHING_MACHINE_YN CHAR(1) CONSTRAINT NN_RM_WASHING_MACHINE_YN NOT NULL,
  REFRIGERATOR_YN CHAR(1) CONSTRAINT NN_RM_REFRIGERATOR_YN NOT NULL,
  AIR_CONDITIONER_YN CHAR(1) CONSTRAINT NN_RM_AIR_CONDITIONER_YN NOT NULL,
  GAS_STOVE_YN CHAR(1) CONSTRAINT NN_RM_GAS_STOVE_YN NOT NULL,
  PET_YN CHAR(1) CONSTRAINT NN_RM_PET_YN NOT NULL,
  ELEVATOR_YN CHAR(1) CONSTRAINT NN_RM_ELEVATOR_YN NOT NULL,
  PARKING_YN CHAR(1) CONSTRAINT NN_RM_PARKING_YN NOT NULL,
  VIEW_NO NUMBER DEFAULT 0,

  CONSTRAINT CK_RM_ROOM_STATUS CHECK(ROOM_STATUS IN ('Y', 'N')),
  CONSTRAINT CK_RM_WASHING_MACHINE_YN CHECK(WASHING_MACHINE_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_REFRIGERATOR_YN CHECK(REFRIGERATOR_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_AIR_CONDITIONER_YN CHECK(AIR_CONDITIONER_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_GAS_STOVE_YN CHECK(GAS_STOVE_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_PET_YN CHECK(PET_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_ELEVATOR_YN CHECK(ELEVATOR_YN IN ('Y', 'N')),
  CONSTRAINT CK_RM_PARKING_YN CHECK(PARKING_YN IN ('Y', 'N')),
  CONSTRAINT FK_RM_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES TBL_ROOM_CATEGORY(CATEGORY_NO),
  CONSTRAINT FK_RM_OFFICE_NO FOREIGN KEY (OFFICE_NO) REFERENCES TBL_OFFICE(OFFICE_NO)
);

  COMMENT ON COLUMN TBL_ROOM.ROOM_NO IS '매물코드';
  COMMENT ON COLUMN TBL_ROOM.ROOM_PRICE IS '매물가격';
  COMMENT ON COLUMN TBL_ROOM.ROOM_STATUS IS '매물상태';
  COMMENT ON COLUMN TBL_ROOM.EXCLUSIVE_AREA IS '전용면적';
  COMMENT ON COLUMN TBL_ROOM.ADDRESS IS '주소';
  COMMENT ON COLUMN TBL_ROOM.CREATE_DATE IS '등록일시';
  COMMENT ON COLUMN TBL_ROOM.CATEGORY_NO IS '매물카테고리';
  COMMENT ON COLUMN TBL_ROOM.OFFICE_NO IS '사무소코드';
  COMMENT ON COLUMN TBL_ROOM.ROOM_FLOOR IS '층정보';
  COMMENT ON COLUMN TBL_ROOM.DIRECTION IS '방향';
  COMMENT ON COLUMN TBL_ROOM.MONTH_COST IS '월관리비';
  COMMENT ON COLUMN TBL_ROOM.COST_INCLUDE IS '관리비포함항목';
  COMMENT ON COLUMN TBL_ROOM.CONSTRUCTION_DATE IS '준공날짜';
  COMMENT ON COLUMN TBL_ROOM.AVAILABLE_DATE IS '입주가능일';
  COMMENT ON COLUMN TBL_ROOM.ROOM_EXPLANATION IS '매물상세설명';
  COMMENT ON COLUMN TBL_ROOM.TRANSPORTATION_INFO IS '교통정보';
  COMMENT ON COLUMN TBL_ROOM.WASHING_MACHINE_YN IS '세탁기';
  COMMENT ON COLUMN TBL_ROOM.REFRIGERATOR_YN IS '냉장고';
  COMMENT ON COLUMN TBL_ROOM.AIR_CONDITIONER_YN IS '에어컨';
  COMMENT ON COLUMN TBL_ROOM.GAS_STOVE_YN IS '인덕션/가스레인지';
  COMMENT ON COLUMN TBL_ROOM.PET_YN IS '반려동물';
  COMMENT ON COLUMN TBL_ROOM.ELEVATOR_YN IS '엘레베이터유무';
  COMMENT ON COLUMN TBL_ROOM.PARKING_YN IS '주차가능여부';
  COMMENT ON COLUMN TBL_ROOM.VIEW_NO IS '조회수';

INSERT INTO TBL_ROOM (ROOM_NO, ROOM_PRICE, EXCLUSIVE_AREA, ADDRESS, CREATE_DATE, CATEGORY_NO, OFFICE_NO, ROOM_FLOOR
  , DIRECTION, MONTH_COST, COST_INCLUDE, CONSTRUCTION_DATE, AVAILABLE_DATE, ROOM_EXPLANATION
  , TRANSPORTATION_INFO, WASHING_MACHINE_YN, REFRIGERATOR_YN, AIR_CONDITIONER_YN, GAS_STOVE_YN, PET_YN, ELEVATOR_YN, PARKING_YN)
VALUES (SEQ_ROOM_NO.NEXTVAL, 50000000, 22.15, '관악구 신림동 1537-1', TO_DATE('21/03/08', 'RR/MM/DD'), 1, 1, '4층/4층'
  , '북향', 80000, '수도, 인터넷, 티비', TO_DATE('94/10/15', 'RR/MM/DD'), '즉시 입주',  '리모델링 분리형 원룸입니다. 양창문이라 환기가 잘되고 깔끔합니다.'
  , '근처 버스정류장 도보 3분', 'Y', 'Y', 'Y', 'Y', 'Y', 'N', 'N');

--매물첨부파일--
CREATE TABLE TBL_ROOM_FILE(
  FILE_NO NUMBER,
  ROOM_NO NUMBER,
  ORIGIN_NAME VARCHAR2(50),
  SAVE_NAME VARCHAR2(100),
  EXTENSION VARCHAR2(50),
  CONTENT VARCHAR2(50),
  SAVE_PATH VARCHAR2(100),
  CONSTRAINT PK_FILE_NO_AND_ROOM_NO PRIMARY KEY (FILE_NO, ROOM_NO),
  CONSTRAINT FK_RF_ROOM_NO FOREIGN KEY (ROOM_NO) REFERENCES TBL_ROOM (ROOM_NO)
);
  COMMENT ON COLUMN TBL_ROOM_FILE.FILE_NO IS '파일번호';
  COMMENT ON COLUMN TBL_ROOM_FILE.ROOM_NO IS '매물코드';
  COMMENT ON COLUMN TBL_ROOM_FILE.ORIGIN_NAME IS '원본파일명';
  COMMENT ON COLUMN TBL_ROOM_FILE.SAVE_NAME IS '저장파일명';
  COMMENT ON COLUMN TBL_ROOM_FILE.EXTENSION IS '파일확장자';
  COMMENT ON COLUMN TBL_ROOM_FILE.CONTENT IS '파일내용';
  COMMENT ON COLUMN TBL_ROOM_FILE.SAVE_PATH IS '저장경로';


---------- 서류보관 ----------
CREATE TABLE TBL_USER_DOCUMENT (
  FILE_NO NUMBER,
  USER_NO NUMBER,
  ORIGIN_NAME VARCHAR2(50) CONSTRAINT NN_UD_ORIGIN_NAME NOT NULL,
  SAVE_NAME VARCHAR2(100) CONSTRAINT NN_UD_SAVE_NAME NOT NULL,
  EXTENSION VARCHAR2(50) CONSTRAINT NN_UD_EXTENSION NOT NULL,
  CONTENT VARCHAR2(50),
  REGISTER_DATE DATE CONSTRAINT NN_UD_REGISTER_DATE NOT NULL,
  ROOM_NO NUMBER CONSTRAINT NN_UD_ROOM_NO NOT NULL,
  SAVE_PATH VARCHAR2(100) CONSTRAINT NN_UD_SAVE_PATH NOT NULL,
  CONSTRAINT PK_FILE_NO_AND_USER_NO PRIMARY KEY(FILE_NO, USER_NO),
  CONSTRAINT FK_USER_NO FOREIGN KEY(USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT FK_ROOM_NO FOREIGN KEY(ROOM_NO) REFERENCES TBL_ROOM (ROOM_NO)
);

COMMENT ON COLUMN TBL_USER_DOCUMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN TBL_USER_DOCUMENT.USER_NO IS '회원번호';
COMMENT ON COLUMN TBL_USER_DOCUMENT.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN TBL_USER_DOCUMENT.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN TBL_USER_DOCUMENT.EXTENSION IS '파일확장자';
COMMENT ON COLUMN TBL_USER_DOCUMENT.CONTENT IS '파일내용';
COMMENT ON COLUMN TBL_USER_DOCUMENT.REGISTER_DATE IS '등록일시';
COMMENT ON COLUMN TBL_USER_DOCUMENT.ROOM_NO IS '매물코드';
COMMENT ON COLUMN TBL_USER_DOCUMENT.SAVE_PATH IS '저장경로';


-------- 찜한 매물 -------
CREATE TABLE TBL_PICK_ROOM (
  USER_NO NUMBER,
  ROOM_NO NUMBER,
  CONSTRAINT PK_PR_USER_NO_AND_ROOM_NO PRIMARY KEY(USER_NO, ROOM_NO),
  CONSTRAINT FK_PR_USER_NO FOREIGN KEY(USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT FK_PR_ROOM_NO FOREIGN KEY(ROOM_NO) REFERENCES TBL_ROOM (ROOM_NO)
);

COMMENT ON COLUMN TBL_PICK_ROOM.USER_NO IS '회원번호';
COMMENT ON COLUMN TBL_PICK_ROOM.ROOM_NO IS '매물코드';

------------------------------------------------------------------ 중개사무소 / 리뷰 / 신고

-------------- 거래내역 ----------------
CREATE TABLE TBL_TRANSACTION_LIST (
  ROOM_NO NUMBER CONSTRAINT PK_TL_ROOM_NO PRIMARY KEY,
  USER_NO NUMBER CONSTRAINT NN_TL_USER_NO NOT NULL,
  OFFICE_NO	NUMBER CONSTRAINT NN_TL_OFFICE_NO NOT NULL,
  TRANSACTION_DATE DATE,
  CONSTRAINT FK_TL_ROOM_NO FOREIGN KEY(ROOM_NO) REFERENCES TBL_ROOM (ROOM_NO),
  CONSTRAINT FK_TL_USER_NO FOREIGN KEY(USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT FK_TL_OFFICE_NO FOREIGN KEY(OFFICE_NO) REFERENCES TBL_OFFICE (OFFICE_NO)
);

COMMENT ON COLUMN TBL_TRANSACTION_LIST.ROOM_NO IS '매물코드';
COMMENT ON COLUMN TBL_TRANSACTION_LIST.USER_NO IS '회원번호';
COMMENT ON COLUMN TBL_TRANSACTION_LIST.OFFICE_NO IS '사무소번호';
COMMENT ON COLUMN TBL_TRANSACTION_LIST.TRANSACTION_DATE IS '거래일자';

----------- 리뷰 -----------
CREATE TABLE TBL_REVIEW (
  REVIEW_NO NUMBER CONSTRAINT PK_REVIEW_NO PRIMARY KEY,
  RATING NUMBER CONSTRAINT NN_RATING NOT NULL,
  REVIEW_CONTENT VARCHAR2(150) CONSTRAINT NN_REVIEW_CONNECT NOT NULL,
  OFFICE_NO NUMBER CONSTRAINT NN_RV_OFFICE_NO NOT NULL,
  USER_NO NUMBER CONSTRAINT NN_RV_USER_NO NOT NULL,
  CREATION_DATE DATE CONSTRAINT NN_CREATION_DATE NOT NULL,
  CONSTRAINT FK_RV_OFFICE_NO FOREIGN KEY(OFFICE_NO) REFERENCES TBL_OFFICE (OFFICE_NO),
  CONSTRAINT FK_RV_USER_NO FOREIGN KEY(USER_NO) REFERENCES TBL_USER (USER_NO)
);

COMMENT ON COLUMN TBL_REVIEW.REVIEW_NO IS '리뷰번호';
COMMENT ON COLUMN TBL_REVIEW.RATING IS '평점';
COMMENT ON COLUMN TBL_REVIEW.REVIEW_CONTENT IS '리뷰내용';
COMMENT ON COLUMN TBL_REVIEW.OFFICE_NO IS '사무소번호';
COMMENT ON COLUMN TBL_REVIEW.USER_NO IS '작성자';
COMMENT ON COLUMN TBL_REVIEW.CREATION_DATE IS '작성일자';

------------ 신고카테고리 -------------
CREATE TABLE TBL_REPORT_CATEGORY (
  CATEGORY_NO NUMBER CONSTRAINT PK_RC_CATEGORY_NO PRIMARY KEY,
  CATEGORY_NAME	VARCHAR2(100) CONSTRAINT NN_RC_CATEGORY_NAME NOT NULL
);

COMMENT ON COLUMN TBL_REPORT_CATEGORY.CATEGORY_NO IS '신고카테고리';
COMMENT ON COLUMN TBL_REPORT_CATEGORY.CATEGORY_NAME IS '신고내용';

INSERT INTO TBL_REPORT_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(1, '허위매물');
INSERT INTO TBL_REPORT_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(2, '가격흥정');
INSERT INTO TBL_REPORT_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(3, '이미 판매된 매물');
INSERT INTO TBL_REPORT_CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES(4, '사진과 다른 매물');

---------- 신고 ------------
CREATE TABLE TBL_REPORT (
  REPORT_NO	NUMBER CONSTRAINT PK_REPORT_NO PRIMARY KEY,
  CATEGORY_NO NUMBER CONSTRAINT NN_RP_CATEGORY_NO NOT NULL,
  USER_NO NUMBER CONSTRAINT NN_RP_USER_NO NOT NULL,
  ROOM_NO NUMBER CONSTRAINT NN_RP_ROOM_NO NOT NULL,
  OFFICE_NO	NUMBER CONSTRAINT NN_RP_OFFICE_NO NOT NULL,
  REPORT_CONTENT VARCHAR2(500) CONSTRAINT NN_REPORT_CONTENT NOT NULL,
  APPROVAL_YN CHAR(1) DEFAULT 'N' CONSTRAINT NN_RP_APPROVAL_YN NOT NULL,
  CONSTRAINT FK_RP_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES TBL_REPORT_CATEGORY (CATEGORY_NO),
  CONSTRAINT FK_RP_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT FK_RP_ROOM_NO FOREIGN KEY (ROOM_NO) REFERENCES TBL_ROOM (ROOM_NO),
  CONSTRAINT FK_RP_OFFICE_NO FOREIGN KEY (OFFICE_NO) REFERENCES TBL_OFFICE (OFFICE_NO),
  CONSTRAINT CK_RP_APPROVAL_YN CHECK (APPROVAL_YN IN ('Y','N'))
);

COMMENT ON COLUMN TBL_REPORT.REPORT_NO IS '신고번호';
COMMENT ON COLUMN TBL_REPORT.CATEGORY_NO IS '신고카테고리';
COMMENT ON COLUMN TBL_REPORT.USER_NO IS '회원번호';
COMMENT ON COLUMN TBL_REPORT.ROOM_NO IS '매물코드';
COMMENT ON COLUMN TBL_REPORT.OFFICE_NO IS '사무소번호';
COMMENT ON COLUMN TBL_REPORT.REPORT_CONTENT IS '신고상세내용';
COMMENT ON COLUMN TBL_REPORT.APPROVAL_YN IS '승인여부';


---------------------------------------------------------- 자유게시판

----- 자유게시판 ------
CREATE TABLE TBL_FREE_BOARD(
  POST_NO NUMBER CONSTRAINT PK_FB_POST_NO PRIMARY KEY,
  POST_TITLE VARCHAR2(100) CONSTRAINT NN_FB_POST_TITLE NOT NULL,
  POST_CONTENT VARCHAR2(4000) CONSTRAINT NN_FB_POST_CONTENT NOT NULL,
  VIEW_NO NUMBER DEFAULT 0,
  CREATION_DATE   DATE CONSTRAINT NN_FB_CREATION_DATE NOT NULL,
  REPORT_COUNT NUMBER DEFAULT 0,
  VIEW_YN CHAR(1) DEFAULT 'Y',
  USER_NO NUMBER CONSTRAINT NN_FB_USER_NO NOT NULL,
  CONSTRAINT FK_FB_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO)
);

COMMENT ON COLUMN TBL_FREE_BOARD.POST_NO IS '게시물번호';
COMMENT ON COLUMN TBL_FREE_BOARD.POST_TITLE IS '게시물제목';
COMMENT ON COLUMN TBL_FREE_BOARD.POST_CONTENT IS '게시물내용';
COMMENT ON COLUMN TBL_FREE_BOARD.VIEW_NO IS '조회수';
COMMENT ON COLUMN TBL_FREE_BOARD.CREATION_DATE IS '작성일자';
COMMENT ON COLUMN TBL_FREE_BOARD.REPORT_COUNT IS '신고건수';
COMMENT ON COLUMN TBL_FREE_BOARD.VIEW_YN IS '노출여부';
COMMENT ON COLUMN TBL_FREE_BOARD.USER_NO IS '작성자';

-- 자유게시판 샘플 추가 --
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '점메추해~~~~', '점심메뉴 추천해줘!!!', TO_DATE('21/03/08', 'RR/MM/DD'), 4);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '아 배고프다.... 점심시간 언제오냐', '메뉴도 쌀국수로 이미 정해놨는데 시간이 너무 안감;;', TO_DATE('21/03/08', 'RR/MM/DD'), 2);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '우리집 강아지 보고가라.', '....뻥이야.. 나만 강아지 없냐..', TO_DATE('21/03/10', 'RR/MM/DD'), 9);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '방구들아 평균 한달 생활비 얼마나 듦?', '나 혼자 사는데 한 달에 100만원 넘게 나옴', TO_DATE('21/03/12', 'RR/MM/DD'), 7);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '중소청전세대출 받은 사람 나 물어볼 거 있음', '서류 준비할 때 시간 얼마나 촉박했어?', TO_DATE('21/03/12', 'RR/MM/DD'), 8);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '전세집 권태기 극복하는 방법', '6개월 정도에 한 번씩은 집 인테리어 구조 싹 바꾸면 ㄹㅇ 새로 이사 온 기분들고 좋음 ㅋㅋ', TO_DATE('21/03/14', 'RR/MM/DD'), 10);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '야근하고 이제 퇴근한다.', '개발자되면 좋을줄만 알았지.... 수료하면 내 세상이 될 줄 알았지...ㅎ', TO_DATE('21/03/15', 'RR/MM/DD'), 11);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '신림역 근처 맛집 추천 좀', '너네만 맛있는 거 먹지말라고!!!', TO_DATE('21/04/03', 'RR/MM/DD'), 6);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '나 큰일났음 낼 이사인데 아직도 못 자는 중;;', '진짜 너무 설레서 잠 못자겠어.... 첫 자취인데 꿀팁 좀 알려줄 수 있을까 방구들아??', TO_DATE('21/04/03', 'RR/MM/DD'), 4);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '니네 야식 뭐 먹었냐?', '난 불닭에 주먹밥!', TO_DATE('21/04/03', 'RR/MM/DD'), 5);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '우리집 인테리어 진짜 멋있음 ㅋ', '근데 안보여줄거야^^', TO_DATE('21/04/03', 'RR/MM/DD'), 2);
INSERT INTO TBL_FREE_BOARD (POST_NO, POST_TITLE, POST_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_FREE_POST_NO.NEXTVAL, '방구들아 이거 집주인이 잘못한 거 맞지?', '집주인이 뭐라고 했냐면 ㅡㅡ', TO_DATE('21/04/08', 'RR/MM/DD'), 3);

-- 자유게시판 첨부파일
CREATE TABLE TBL_FREE_BOARD_FILE(
  FILE_NO NUMBER,
  POST_NO NUMBER,
  ORIGIN_NAME VARCHAR2(50) CONSTRAINT NN_ORIGIN_NAME NOT NULL,
  SAVE_NAME VARCHAR2(50) CONSTRAINT NN_SAVE_NAME NOT NULL,
  EXTENSION   VARCHAR2(50) CONSTRAINT NN_EXTENSION NOT NULL,
  CONTENT VARCHAR2(50),
  SAVE_PATH   VARCHAR2(100) CONSTRAINT NN_SAVE_PATH NOT NULL,
  CONSTRAINT PK_FILE_NO_AND_POST_NO PRIMARY KEY (FILE_NO, POST_NO),
  CONSTRAINT FK_POST_NO FOREIGN KEY (POST_NO) REFERENCES TBL_FREE_BOARD (POST_NO)
);

COMMENT ON COLUMN TBL_FREE_BOARD_FILE.FILE_NO IS '파일번호';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.POST_NO IS '게시물번호';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.EXTENSION IS '파일확장자';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.CONTENT IS '파일내용';
COMMENT ON COLUMN TBL_FREE_BOARD_FILE.SAVE_PATH IS '저장경로';

-- 댓글
CREATE TABLE TBL_REPLY(
  REPLY_NO NUMBER,
  POST_NO NUMBER,
  REPLY_CONTENT VARCHAR2(500) CONSTRAINT NN_REPLY_CONTENT NOT NULL,
  CREATION_DATE   DATE CONSTRAINT NN_RE_CREATION_DATE NOT NULL,
  REPORT_COUNT NUMBER DEFAULT 0,
  VIEW_YN CHAR(1) DEFAULT 'Y',
  USER_NO NUMBER CONSTRAINT NN_RE_USER_NO NOT NULL,
  CONSTRAINT PK_REPLY_NO_AND_POST_NO PRIMARY KEY (REPLY_NO, POST_NO),
  CONSTRAINT FK_RE_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO)
);

COMMENT ON COLUMN TBL_REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN TBL_REPLY.POST_NO IS '게시물번호';
COMMENT ON COLUMN TBL_REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN TBL_REPLY.CREATION_DATE IS '작성일자';
COMMENT ON COLUMN TBL_REPLY.REPORT_COUNT IS '신고건수';
COMMENT ON COLUMN TBL_REPLY.VIEW_YN IS '노출여부';
COMMENT ON COLUMN TBL_REPLY.USER_NO IS '작성자';

-- 댓글 샘플 추가 --
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 1, '나랑 같이 쌀국수 먹자!!', TO_DATE('21/03/08', 'RR/MM/DD'), 2);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 2, '배고파 죽겠다 진짜.. 나는 오늘 짬뽕먹을거임.', TO_DATE('21/03/08', 'RR/MM/DD'), 9);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 3, '아 뭐야 기대했는데.. 나도 없어.....', TO_DATE('21/03/10', 'RR/MM/DD'), 8);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 4, '나는 한 80만원 정도?? 왜 그렇게 많이 쓰는거야ㅋㅋㅋ', TO_DATE('21/03/12', 'RR/MM/DD'), 5);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 5, '이사 하루 전날에 나오는 경우도 많다던데 나는 한 일주일 전에 나온듯?', TO_DATE('21/03/12', 'RR/MM/DD'), 7);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 6, '오 나 안그래도 어제 인테리어 한 번 바꿈 ㅎㅇㅎㅇ', TO_DATE('21/03/14', 'RR/MM/DD'), 11);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 7, 'ㅋㅋ나도 개발자인데....힘내자 ㅋ..', TO_DATE('21/03/15', 'RR/MM/DD'), 10);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 8, '안알랴줌ㅎ', TO_DATE('21/04/03', 'RR/MM/DD'), 3);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 9, '오늘은 자취할 때 꿀팁을 알려드릴거예요!! 그나저나 자취를 하면서 여러가지 아이템들을 사다보니 너무 돈이 많이 나간 거 아세요?ㅠㅠ 하지만 이 자취 아이템을 사고나니 제 삶의 질이 정말 달라졌어요!!! 자취하실 때 주머니 사정 잘 고려해가면서 자취템 하나 정도는 장만하시는 것도 좋을 것 같아요! 그럼 안녕~', TO_DATE('21/04/03', 'RR/MM/DD'), 6);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 10, '난 양꼬치랑 칭따오~~~~~~', TO_DATE('21/04/03', 'RR/MM/DD'), 4);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 11, '...여기 전체적으로 이상한 애들이 많은 것 같음..', TO_DATE('21/04/03', 'RR/MM/DD'), 9);
INSERT INTO TBL_REPLY (REPLY_NO, POST_NO, REPLY_CONTENT, CREATION_DATE, USER_NO)
VALUES (SEQ_REPLY_NO.NEXTVAL, 12, '어쨌든 집주인이 잘못한거임', TO_DATE('21/04/08', 'RR/MM/DD'), 8);

-- 이용권
CREATE TABLE TBL_MEMBERSHIP(
  MEMBERSHIP_NO NUMBER CONSTRAINT PK_MEMBERSHIP_NO PRIMARY KEY,
  MEMBERSHIP_NAME VARCHAR2(50) CONSTRAINT NN_MEMBERSHIP_NAME NOT NULL,
  MEMBERSHIP_PRICE NUMBER CONSTRAINT NN_MEMBERSHIP_PRICE NOT NULL,
  MEMBERSHIP_PERIOD   NUMBER CONSTRAINT NN_MEMBERSHIP_PERIOD NOT NULL
);

COMMENT ON COLUMN TBL_MEMBERSHIP.MEMBERSHIP_NO IS '이용권코드';
COMMENT ON COLUMN TBL_MEMBERSHIP.MEMBERSHIP_NAME IS '이용권이름';
COMMENT ON COLUMN TBL_MEMBERSHIP.MEMBERSHIP_PRICE IS '이용권가격';
COMMENT ON COLUMN TBL_MEMBERSHIP.MEMBERSHIP_PERIOD IS '이용권기간';

-- 이용권 샘플 추가 --
INSERT INTO TBL_MEMBERSHIP (MEMBERSHIP_NO, MEMBERSHIP_NAME, MEMBERSHIP_PRICE, MEMBERSHIP_PERIOD)
VALUES (SEQ_MEMBERSHIP_NO.NEXTVAL, '기본 이용권', 200000, 1);

-- 결제내역
CREATE TABLE TBL_PAYMENT_LIST(
  PAYMENT_NO NUMBER   CONSTRAINT PK_PAYMENT_NO PRIMARY KEY,
  EXPIRATION_DATE DATE CONSTRAINT NN_EXPIRATION_DATE NOT NULL,
  PAYMENT_DATE DATE CONSTRAINT NN_PAYMENT_DATE NOT NULL,
  MEMBERSHIP_NO   NUMBER CONSTRAINT NN_MEMBERSHIP_NO NOT NULL,
  USER_NO NUMBER CONSTRAINT NN_USER_NO NOT NULL,
  CONSTRAINT FK_MEMBERSHIP_NO FOREIGN KEY (MEMBERSHIP_NO) REFERENCES TBL_MEMBERSHIP (MEMBERSHIP_NO),
  CONSTRAINT FK_PL_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO)
);

COMMENT ON COLUMN TBL_PAYMENT_LIST.PAYMENT_NO IS '결제번호';
COMMENT ON COLUMN TBL_PAYMENT_LIST.EXPIRATION_DATE IS '유효기간';
COMMENT ON COLUMN TBL_PAYMENT_LIST.PAYMENT_DATE IS '결제일';
COMMENT ON COLUMN TBL_PAYMENT_LIST.MEMBERSHIP_NO IS '이용권코드';
COMMENT ON COLUMN TBL_PAYMENT_LIST.USER_NO IS '회원번호';


-------------------------------------------------------------------------- 공지, 정보, 통계


CREATE TABLE TBL_NOTICE(
  NOTICE_NO NUMBER CONSTRAINT PK_NOTICE_NO PRIMARY KEY,
  VIEW_NO NUMBER,
  CREATION_DATE DATE CONSTRAINT NN_NT_CREATION_DATE NOT NULL,
  MODIFICATION_DATE DATE,
  NOTICE_STATUS_YN CHAR(1) DEFAULT 'Y',
  USER_NO NUMBER CONSTRAINT NN_NT_USER_NO NOT NULL,
  TITLE VARCHAR2(50) CONSTRAINT NN_NT_TITLE NOT NULL,
  CONTENT VARCHAR2(500) CONSTRAINT NN_NT_CONTENT NOT NULL,
  CONSTRAINT FK_NT_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO),
  CONSTRAINT CK_NOTICE_STATUS_YN CHECK(NOTICE_STATUS_YN IN ('Y', 'N'))
   
);

COMMENT ON COLUMN TBL_NOTICE.NOTICE_NO IS '공지사항번호';
COMMENT ON COLUMN TBL_NOTICE.VIEW_NO IS '조회수';
COMMENT ON COLUMN TBL_NOTICE.CREATION_DATE IS '작성일자';
COMMENT ON COLUMN TBL_NOTICE.MODIFICATION_DATE IS '수정일자';
COMMENT ON COLUMN TBL_NOTICE.USER_NO IS '작성자';
COMMENT ON COLUMN TBL_NOTICE.TITLE IS '글제목';
COMMENT ON COLUMN TBL_NOTICE.CONTENT IS '글내용';
COMMENT ON COLUMN TBL_NOTICE.NOTICE_STATUS_YN IS '공지상태';



CREATE TABLE TBL_CONNECT_STATISTIC(
  CONNECT_DATE DATE CONSTRAINT PK_CONNECT_DATE PRIMARY KEY,
  CONNECT_COUNT NUMBER
);

COMMENT ON COLUMN TBL_CONNECT_STATISTIC.CONNECT_DATE IS '접속일자';
COMMENT ON COLUMN TBL_CONNECT_STATISTIC.CONNECT_COUNT IS '접속자수';



CREATE TABLE TBL_ROOM_STATISTIC(
  ROOM_REGISTER_DATE NUMBER CONSTRAINT PK_ROOM_REGISTER_DATE PRIMARY KEY,
  ROOM_COUNT NUMBER
);

COMMENT ON COLUMN TBL_ROOM_STATISTIC.ROOM_REGISTER_DATE IS '등록일자';
COMMENT ON COLUMN TBL_ROOM_STATISTIC.ROOM_COUNT IS '매물등록수';


CREATE TABLE TBL_INFO_CATEGORY(
  CATEGORY_NO NUMBER CONSTRAINT PK_IC_CATEGORY_NO PRIMARY KEY,
  CATEGORY_NAME   VARCHAR2(50) CONSTRAINT NN_IC_CATEGORY_NAME NOT NULL
);

COMMENT ON COLUMN TBL_INFO_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN TBL_INFO_CATEGORY.CATEGORY_NAME IS '카테고리이름';

INSERT INTO TBL_INFO_CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(1, '계약시주의사항');
INSERT INTO TBL_INFO_CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES (2, '청년전세대출');
INSERT INTO TBL_INFO_CATEGORY(CATEGORY_NO, CATEGORY_NAME) VALUES(3, '기타');

CREATE TABLE TBL_INFO_BOARD(
  POST_NO NUMBER CONSTRAINT PK_POST_NO PRIMARY KEY,
  POST_TITLE VARCHAR2(50) CONSTRAINT NN_IB_POST_TITLE NOT NULL,
  POST_CONTENT VARCHAR2(4000) CONSTRAINT NN_IB_POST_CONTENT NOT NULL,
  VIEW_NO NUMBER DEFAULT 0,
  CREATION_DATE   DATE CONSTRAINT NN_IB_CREATION_DATE NOT NULL,
  CATEGORY_NO NUMBER CONSTRAINT NN_IB_CATEGORY_NO NOT NULL,
  USER_NO NUMBER CONSTRAINT NN_IB_USER_NO NOT NULL,
  CONSTRAINT FK_IB_CATEGORY_NO FOREIGN KEY (CATEGORY_NO) REFERENCES TBL_INFO_CATEGORY (CATEGORY_NO),
  CONSTRAINT FK_IB_USER_NO FOREIGN KEY (USER_NO) REFERENCES TBL_USER (USER_NO)
);

COMMENT ON COLUMN TBL_INFO_BOARD.POST_NO IS '정보게시물번호';
COMMENT ON COLUMN TBL_INFO_BOARD.POST_TITLE IS '게시물제목';
COMMENT ON COLUMN TBL_INFO_BOARD.POST_CONTENT IS '게시물내용';
COMMENT ON COLUMN TBL_INFO_BOARD.VIEW_NO IS '조회수';
COMMENT ON COLUMN TBL_INFO_BOARD.CREATION_DATE IS '작성일자';
COMMENT ON COLUMN TBL_INFO_BOARD.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN TBL_INFO_BOARD.USER_NO IS '회원번호';

CREATE TABLE TBL_INFO_BOARD_FILE(
  FILE_NO NUMBER,
  POST_NO NUMBER,
  ORIGIN_NAME VARCHAR2(50) CONSTRAINT NN_IBF_ORIGIN_NAME NOT NULL,
  SAVE_NAME   VARCHAR2(50) CONSTRAINT NN_IBF_SAVE_NAME NOT NULL,
  EXTENSION   VARCHAR2(50) CONSTRAINT NN_IBF_EXTENSION NOT NULL,
  CONTENT VARCHAR2(50),
  SAVE_PATH   VARCHAR2(100) CONSTRAINT NN_IBF_SAVE_PATH NOT NULL,
  CONSTRAINT PK_IBF_FILE_NO_AND_POST_NO PRIMARY KEY(FILE_NO, POST_NO),
  CONSTRAINT FK_IBF_POST_NO FOREIGN KEY (POST_NO) REFERENCES TBL_INFO_BOARD (POST_NO)
);

COMMENT ON COLUMN TBL_INFO_BOARD_FILE.FILE_NO IS '파일번호';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.POST_NO IS '정보게시물번호';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.ORIGIN_NAME IS '원본파일명';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.SAVE_NAME IS '저장파일명';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.EXTENSION IS '파일확장자';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.CONTENT IS '파일내용';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.SAVE_PATH IS '저장경로';
COMMENT ON COLUMN TBL_INFO_BOARD_FILE.FILE_NO IS '파일번호';



INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '이사 전 잊지 말자! 준비 체크리스트'
, '"이사를 앞두고 있다면 짐을 꾸리는 것부터 시작해 이삿짐센터 선택까지 신경 써야 할 일이 한두 가지가 아니다. 차질 없는 이사의 진행을 위해서는 이사 준비 체크리스트를 작성해서 빠짐없이 꼼꼼히 챙겨야 한다.

그렇게 챙기고도 꼭 무언가 하나는 빠뜨리게 되는 큰 일인 만큼 시행착오 없는 이사 준비를 위해 필요한 사항들을 정리해보았다. 이사 전 잊지 말아야 할 체크리스트!

잔금과 이체 한도를 확인하자





현금과 이체 중 어떻게 잔금을 치를지를 결정하고, 잔금을 이삿날 모두 이체 혹은 출금할 수 있도록 한도를 확인해야 한다. 만일 인터넷뱅킹을 사용할 경우 이체 한도가 문제가 된다면 잔금을 치르지 못해 난처한 상황이 생길 수 있으므로 필수적으로 준비해 놓아야 한다.

관리사무소에 이삿날을 통보하자





이삿날 이삿짐 차량과 사다리차를 주차해야 하므로 날짜와 시간을 미리 통보해야 한다. 이는 이사를 나가는 집뿐 아니라 들어가는 집도 마찬가지이다. 사다리차를 사용하지 못하는 세대가 있을 수도 있으니 짐을 옮길 수 있는 주차장 자리도 확보해 놓아야 하므로 사전 통보는 필수.

냉장고 속 비우기





아무리 이삿짐센터에서 아이스박스를 가지고 온다고 해도, 국물이 많거나 금방 상하는 음식이 있으면 이사 중 손상이 가기 쉽다. 게다가 날씨가 무더운 요즘 같은 경우는 더욱 그렇다. 사전에 냉장고를 최대한 비워 짐을 줄이고 전기밥솥의 밥도 비워두는 것이 좋다.

반려동물 맡아줄 사람 찾기





반려동물들이 있는 경우 이삿날 함께 한다면 먼지가 많이 발생하기도 하고 사이즈가 큰 가전이나 가구를 옮기며 부상의 위험이 있을 수도 있다. 또한 밖에서 보내야 하는 시간이 많고 주인이 이사에 바빠 신경을 써주기 힘들기 때문에 반려동물을 맡아줄 기관이나 친지 등 사람을 미리 찾아 부탁하는 것이 좋다."'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약하려는데…"임대인이 법인?"'
, '“와! 전세인데도 도배는 물론이고 인테리어가 너무 예쁘게 잘 되어있네요! 마음에 듭니다. 바로 계약할게요.”


임차인은 바로 계약서를 작성하려 했으나 임대인이 법인이라는 말을 듣고 잠시 망설여졌다. 임대인이 법인일 경우 문제가 있을 수도 있다는 말을 어디선가 들었기 때문이다.


2017년 8·2 부동산 대책 이후로 법인 명의의 임대인이 부쩍 늘었다. 개인 소유 주택에 대한 규제가 점점 강해지면서 법인을 설립해 임대사업을 하는 경우가 점점 많아지고 있는 것이다. 임대인이 법인이라는 말을 들으면 왠지 모르게 불안감을 느끼게 된다.


하지만 왜 불안한지 그 이유에 대해서는 잘 모르는 경우가 대부분이다. 하물며 중개하는 공인중개사 입장에서도 크게 다르지 않다. 그렇다면 임대인이 법인일 경우 과연 문제가 있을까? 만약 있다면 어떤 이유로 그런 것이며 예방책은 있는 것일까? 임대인이 법인일 경우 개인과 다른 점이 무엇인지 정리하면서 살펴보도록 한다.


임대인이 법인일 경우 가장 먼저 드는 걱정은 ‘내 보증금이 안전할까?’에 대한 것이다. 이와 관련해 법인에 관한 잘못된 인식은 다음과 같다.


임대인이 법인이라고요? 괜찮을까요?


법인은 경매로 진행될 가능성이 높다?
임대인이 법인일 경우 보증금 반환이 어려울 것이라는 인식이 있다. 보증금 반환 문제가 생기는 대표적인 경우는 임대인이 채무를 상환하지 못해서 해당 주택이 경매로 진행되는 것이다. 이때 임대인이 개인일 경우 통상적인 시각은 불안정한 ‘사업자’라는 인식보다 안정적인 ‘직장인’이라는 인식이 강하기 때문에 개인소유의 부동산은 경매로 진행될 가능성이 적다고 생각하며, 반대로 임대인이 법인일 경우 사업이 잘 안되면 언제든 망할 수 있다는 인식으로 인해 경매가 진행될 가능성이 높다고 생각한다.


하지만 조금만 생각해보면 이런 생각이 모순이라는 것을 알 수 있다. 개인의 경우도 사업을 하는 사업자의 비중이 작지 않고, 직장인이라 해도 해당 회사(법인)가 망한다면 직원 또한 그 피해에서 자유로울 수 없기 때문이다.


그리고 실제로도 경매로 진행되는 부동산 중 법인소유의 물건이 차지하는 비중은 평균적으로 0.5%도 되지 않는다. 2019년 한해 동안 주거용 부동산이 경매로 낙찰된 사건은 총 20,500여건인데 그 중 소유자가 법인인 물건은 100여건에도 훨씬 미치지 못했다. 즉, 경매로 진행되는 대부분의 부동산 소유자는 법인이 아닌 개인이다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약하려는데…"임대인이 법인?2"'
, '법인은 경매 진행 시 임차인이 보증금을 배당받기 어렵다?
이 내용에 대해서는 아예 틀린 말은 아니지만 가장 많은 사람이 오해하고 있는 부분이라 무엇보다 정확히 알아야 할 필요가 있다.


경매가 진행되고 낙찰자가 잔금을 내면 법원은 그 돈을 법에서 정해진 순서에 따라 채권자들에게 나누어주며 이 절차를 배당이라 한다. 임차인도 채권자에 해당하기 때문에 경매 절차에서 자신의 보증금을 배당받게 되는데 위에서 말한 ‘보증금을 배당받기 어렵다’라는 의미는 법에서 정해진 배당순서를 어느 정도 알아야만 위험 여부를 판단할 수 있다.


배당순서를 간단하게 설명하자면 등기사항전부증명서(보통 등기부등본이라 하며 이하 ‘등기부’라 한다)상에 등기된 순서라고 이해하면 된다. 물론 물권, 채권에 따른 배당방식이 다르지만 간단하게 예를 들자면 등기부에 A: 2020.1.5. 근저당 1억, B: 2020.1.7. 근저당 5천만원이 등기되어있다면 당연히 A를 먼저 배당해주고 그다음 돈이 남으면 B를 배당해 주는 것이다.


여기에 전세금 1억원인 임차인이 해당 주택에 2020년 1월 3일에 이사를 들어오면서 전입신고 및 확정일자를 받았다면 임차인은 마치 2020년 1월 4일 0시부로 등기부에 근저당을 설정한 것과 비슷한 지위를 갖게 되며, 그런 이유로 임차인이 A보다 먼저 배당을 받게 된다. 등기된 날짜, 시간 순서대로 배당되는 것이니 매우 간단한 원리이며 임차인의 순서가 가장 빠를 경우 보증금을 배당받는데 특별히 불안해할 이유도 없다.


하지만 예외가 있는데 그것이 바로 임대인이 체납한 세금과 4대 보험료, 그리고 미지급한 임금에 대한 최우선 변제 임금 채권이다. 우리가 법인 물건은 보증금 회수가 불안하다고 느끼는 핵심적인 원인이다.


먼저 세금과 4대 보험료는 배당되는 순서가 법정기일, 납부기한이다. 법정기일이란 해당 세금 납부고지서 발송일 또는 신고일, 확정일이다. 당연히 등기부에 나와 있지도 않고 그 날짜와 금액 또한 알 수 없다. 만약 이들의 순서가 임차인보다 빠르고 금액도 크다면 임차인이 자신의 보증금을 배당받는 것에 차질이 생길 수 있다는 것이다.


그리고 이런 문제는 임대인이 개인이든, 법인이든 마찬가지다. 물론 상대적으로 법인이 개인보다 체납 세금이나 체납 보험료가 많을 가능성이 높겠지만 임대인이 개인이라도 만약 임차인이 들어오는 시점 이전에 이미 큰 금액의 세금이나 4대 보험료가 체납되어 있다면, 임차인의 배당순서는 이다음으로 밀리게 되며, 보증금 상당수를 배당받지 못할 가능성이 커진다. 하지만 이에 대해서는 임차인은 물론 공인중개사도 신경 쓰는 경우를 본 적이 없다. 즉, 임대인의 체납된 세금과 보험료에 대한 문제는 그 주체가 개인이든 법인이든 비슷한 위험요소를 가지고 있다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약하려는데…"임대인이 법인?3"'
, '위험요소에 대한 예방책은?
당연히 있다. 임차인이 입주하는 시점에 해당 임대인에게 국세, 지방세 완납증명서와 4대 보험 납부 확인서를 받으면 된다. 그 시점까지 체납된 세금과 4대 보험이 없다는 것을 확인하면 되는 것이다. 그리고 거듭 강조하지만 이는 임대인이 개인이라 해도 마찬가지다.



오히려 임대인이 개인인 경우 이런 서류들을 확인하는 경우가 거의 없기 때문에 임대인이 사업자인지, 사업자라면 얼마나 많은 직원이 있는지를 확인할 수 없지만 법인일 경우 직원이 없거나 소수인 것을 확인한다면 위험요소를 줄일 수 있다.



실질적으로 임대사업을 하는 법인은 직원이 없는 경우가 대부분이다. 하지만 임대인이 개인사업자로 다섯 명의 직원을 둔 식당을 운영하고 있다면 오히려 세금 및 직원 4대보험 체납으로 인한 위험성이 더 높다고 할 수 있다.



그리고 또 하나의 암초는 위에서 언급했던 최우선변제 임금채권이다. 임금이 체납될 경우 주택 소액보증금과 마찬가지로 최종 3년간의 퇴직금, 3개월 간의 임금, 휴업수당에 해당하는 금액은 등기부의 다른 어떤 권리보다도 최우선 순위로 배당된다.



만약 임대인의 직원이 5명이고 이들 임금이 체납되어 최우선변제 임금채권에 해당하는 금액이 각 500만원이라면 2,500만원에 대해서는 근저당 등과 같은 권리는 물론, 임차인 보증금의 배당순서보다 우선하여 배당되기 때문에 이 또한 임차인이 자신의 보증금을 배당받는데 있어서 문제가 될 수 있는 것이다.



이 또한 임대인이 개인이든 법인이든 마찬가지다. 개인이라 해도 사업을 하고 있고 직원들이 있다면 동일한 위험요소가 존재하는 것이다. 단, 법인이 상대적으로 더 많은 직원이 있을 가능성이 높다는 것일 뿐이다.



하지만 앞서 이야기했듯이 2019년 한해 동안 주거용 부동산이 경매로 낙찰된 사건은 총 20,500여건이었는데 그 중 미지급 임금채권이 신고된 물건은 170여건이었고 더 놀라운 사실은 그 170여건 중 소유자가 법인인 물건은 45건에 불과했다. 나머진 전부 소유자가 개인인 물건이었던 것이다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약하려는데…"임대인이 법인?4"'
, '그런데 임대업을 하는 법인 대부분은 1인 법인이다. 즉, 직원 없이 대표 1인만 법인을 운용하는 구조이다. 이럴 경우 최우선 변제 임금채권에 대한 위험이 전혀 없어진다. 게다가 법인대표가 해당 법인으로부터 급여를 받고 있다 해도 이는 최우선 변제 임금채권의 대상이 아니므로 임차인 입장에서는 배당에 있어서 전혀 문제 될 것이 없다. 직원이 대표 한 명뿐이라는 사실은 4대 보험 납부확인서를 받으면 알 수 있다.



게다가 위 통계자료인 미지급 임금채권이 신고된 사건 중 소유자가 법인인 부동산은 45건에 불과하다고 했는데 그 중 부동산 임대업종의 1인 법인은 놀랍게도 총 두 세 건에 불과했다. 즉, 20,500여건의 경매물건 중 우리가 그토록 우려하는 1인법인의 물건은 단 두 세 건으로 사실상 문제가 발생될 확률이 거의 없다고 말해도 과언이 아닌 것이다.



그렇다면 만약 임차인이 입주한 후에 임대인이 직원을 늘리고 급여를 체납할 경우도 있지 않을까? 그럴 수도 있다. 하지만 그럴 가능성은 임대인이 일반적인 사업을 하는 개인일 경우가 훨씬 높다. 임대사업을 하는 법인은 실질적으로 직원의 수요가 별로 없기 때문이다.



지금까지 임차인의 배당순서와 관련된 내용을 정리했는데 여기서 가장 중요한 내용이 하나 더 있다. 임차인이 이사 들여오면서 전입신고를 하는 시점에 등기부에 아무런 내용이 없다면 앞서 설명했듯이 임차인의 지위가 가장 빠른 상황이 되는데 경매사건에서는 이를 대항력 있는 임차인이라 한다.



이 상황에서는 만약 임차인이 보증금 전액을 다 배당받지 못할 경우 임차인은 나머지 금액을 낙찰자에게 돌려받기 전까지는 해당 주택에서 나가지 않아도 되는 권리를 가지고 있게 된다. 즉, 임차인이 대항력이 있으면 지금까지의 복잡한 문제로 보증금을 배당받는 순서에는 문제가 있을 수 있지만, 결과적으로 보증금을 손해 본 채 해당 주택에서 쫓겨날 일은 없다는 것이다.



더 간단히 정리하자면, 임차인이 입주하는 시점에 해당주택 등기부에 아무런 내용이 없다면 임차인은 임대인이 개인이든, 법인이든 집값이 떨어지지 않는 한 보증금을 손해 볼 가능성이 없는 것이다. 그래도 정 불안하다면 법인대표에게 보증금 반환에 대한 연대책임을 요청하여 특약사항에 기재하는 것도 하나의 방법이다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약하려는데…"임대인이 법인?5"'
, '전세자금대출과 전세보증보험은?
임대인이 법인이면 전세자금대출이 어려울까? 이 또한 사실과 다르다. 임대인이 법인일 경우 전세자금대출을 취급하는 기관이 줄어드는 것은 맞지만 한국주택금융공사라든지, LH에서는 여전히 전세자금대출을 받을 수가 있다. 한국주택금융공사의 경우 임차인의 증빙되는 소득기준 3.5배 정도의 전세자금대출이 가능하며, LH의 경우 오히려 임차인의 소득수준이 낮은 조건에 부합한다면 매우 저렴한 금리의 전세자금대출을 받을 수 있다.



만약 전세자금대출이 반드시 필요한 경우라면 사전에 이 부분을 먼저 확인 후 임대차계약을 진행하면 될 것이다.



전세보증보험도 마찬가지로 취급하는 기관이 제한되는 건 사실이지만 불가능한 것은 아니다. 주택도시보증공사(HUG)에서는 임대인이 법인이라 해도 일정 요건에 충족되면 전세보증보험(정확한 명칭은 전세보증금반환보증) 가입이 가능하다.



지금까지 임대인이 법인일 경우 문제가 될만한 내용에 대해 살펴봤는데 정작 법인이기 때문에 위험한 요소는 미미했으며, 그마저도 임대인에게 몇 가지 서류만 요청해서 확인할 경우 문제가 없다는 것을 알 수 있다. 오히려 법인은 이유 없는 차별을 받기 때문에 이를 만회(?)하기 위해 위에서 예시했듯이 전세임에도 도배, 장판은 물론 높은 수준의 인테리어를 하는 경우가 많다. 게다가 거주기간 동안 시설의 하자나 수선이 필요할 경우 법인은 지출내용 전부가 회계상 비용 처리되기 때문에 개인보다 더 적극적으로 조치해주는 경우가 많다.



이 모든 것을 종합해본다면 임차인 입장에선 몇 가지 서류만 확인한다면 오히려 임대인이 개인인 것 보다 법인인 것이 더 유리하다고 볼 수 있다.



불안함이란 잘 모르는 데서 발생한다. 지금까지의 내용을 확인했다면 더 이상 법인 임대인을 불안해하며 꺼릴 이유는 없을 것이다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '중도금이 중요한 이유'
, '트루 내 집 마련 스토리 #1
얼마 전 A씨로부터 아래와 같이 계약을 해제하고 싶다는 연락을 받았다.

“소장님, 2년 전 계약만 하면 잔금 전까지 책임지고 팔아주겠다는 말만 믿고 아파트 분양계약을 했는데 아직도 팔리지 않고 있습니다. 잔금 마련할 돈도 없어서 계약을 포기하고 싶은데 어떻게 해야 하나요?”



평소에도 이런 문의를 많이 받는데 필자는 중도금 실행이 되었느냐를 가장 먼저 확인한다.

계약 포기를 하고 싶을 때 가장 중요한 핵심은 바로 중도금이기 때문이다.


해약금에 의한 계약해제
민법에 따르면 주(主)된 계약인 매매계약의 종(從)된 계약인 계약금 계약은 계약 체결의 증거로서의 의미인 증약금(證約金)과 해제권을 보류하는 성질인 해약금(解約金), 채무이행을 확보하기 위한 성질인 위약금(違約金) 이렇게 세 가지 성질이 있다.



계약금을 포기하고 계약을 없던 것으로 하고 싶어 하는 분들이 알아야 할 부분은 바로 해약금이다.

해약금에 의한 계약해제를 규정하고 있는 민법 565조에 따르면 매매의 당사자가 계약 당시에 금전 등 계약금 명목으로 상대방에게 교부한 때에는 당사자 간에 다른 약정이 없는 한 당사자의 일방이 이행에 착수할 때까지 교부자는 이를 포기하고 수령자는 그 배액을 상환하여 매매계약을 해제할 수 있다고 되어있다.



법률용어는 왜 이렇게 읽고도 이해가 안 되게 만들었는지 모르겠지만 쉽게 설명하면 매매 계약에 따른 계약금을 지급한 경우 매수자(사는 사람)는 지급한 계약금을 포기하고 계약을 해제할 수 있으며, 매도자(파는 사람)는 받은 계약금의 배액을 반환함으로써 계약을 해제할 수 있다는 말이다.



가끔 매수인은 계약금만 포기하면 되는데 매도인은 왜 배액을 상환해야 하느냐고 따지시는 분들이 있는데 계약해제의 페널티로 매수인은 피 같은 계약금을 포기한다면 매도인 역시 받은 계약금 반환과 더불어 계약금만큼의 돈을 페널티로 지급하는 것이 당연하지 않을까?



이렇듯 매수인은 지급한 계약금을 포기하고, 매도인은 받은 계약금에 그만큼의 돈을 더해서 배액을 상환하면서 계약을 해제할 수 있다.



여기서 끝나면 아무런 분쟁이 없을 것이고 A씨도 납입한 계약금을 포기하고 깔끔하게 계약해제를 할 수 있겠지만 법의 단서조항을 꼼꼼히 살펴보면 그렇게 간단하지 않음을 알 수 있다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '중도금이 중요한 이유2'
, '중도금이 중요한 이유
위에 설명한 해약금에 의한 계약해제(민법 565조) 내용에서 “당사자의 일방이 이행에 착수할 때까지”라는 단서조항이 나온다.



‘이행에 착수’란 채무이행 일부를 행하거나 이행에 필요한 전제를 하는 것으로 쉽게 말하면 중도금을 지급하거나 잔금을 준비하고 등기소에 동행할 것을 촉구하는 등의 행위를 의미한다.



결국 중도금 지급하기 전까지는 해약금에 의한 계약해제가 가능하지만 중도금을 지급하고 나면 매수인은 계약금을 포기하더라도, 매도인은 배액을 상환하더라도 일방적인 계약해제를 할 수 없다는 것이다. 해약금에 의한 계약해제가 되면 소급적 무효가 되며 원상회복의무 및 손해배상청구도 없어진다. 한마디로 깔끔하게 리셋이 되어 버리기 때문에 나는 손해 많이 보았는데 억울하다 손해배상하겠다 이런 것들이 다 의미가 없어진다.



A씨의 경우 중도금을 지급하지 않았다면 지불한 계약금을 포기하고 계약해제를 할 수 있겠지만 중도금이 들어갔다면 계약금을 포기하더라도 일방적 계약해제를 할 수 없다.


그래서 계약할 때의 중도금은 계약해제를 두고 매우 중요한 논점이 된다.



중도금이 들어갔다면 계약금 포기에 의한 일방적 계약해제가 될 수 없고 반드시 양 당사자 협의를 통해서만 해제할 수 있다. 



부동산 시장이 과열되면서 하루가 다르게 아파트 가격이 급등하는 상황이라면 매수자(사는 사람)는 중도금을 하는 것이 유리할 것이고 매도자(파는 사람)는 중도금이 없는 계약을 하는 것이 유리할 것이다. 반대로 집값이 하락하는 상황이라면 매수자는 중도금을 하지 않는 것이, 매도자는 중도금을 받는 것이 유리하다.



예를 들어 10억 원의 아파트를 계약금 1억 원에 계약했는데 계약하자마자 아파트 가격이 급등하면서 잔금 시점에 시세가 13억 원이 되었다면 매도자인 집주인 입장에서는 잔금을 받고 계약을 마무리하는 것보다 해약금 1억 원 주더라도 계약해제한 후 새로운 매수자에게 13억 원에 매매하는 것이 1억 원 더 유리할 것이다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '중도금이 중요한 이유3'
, '법으로 보장된 계약금에 의한 계약해제를 하는데 욕할 사람은 없다.



매수인 입장에서는 계약한 후 집값이 3억 원이나 올라 기분 좋아하고 있는데 집주인이 1억 원 주고 계약을 해제하겠다고 하면 1억 원 더 받았어도 결코 기분이 좋지 않다. 왜냐면 다시 구입하려고 하면 시세가 올라 이제는 13억 원에 구입해야 하기 때문이다.



정리하면 계약이 깨어지지 않고 반드시 이행되기를 원한다면 계약 시 중도금을 포함하는 것이 좋겠고 특약사항에 중도금 날짜 이전에도 중도금 입금할 수 있다는 특약사항 넣어두고 빨리 중도금을 입금하는 것이 유리할 것이다.

반면 A씨와 같이 잔금까지 갈 생각이 전혀 없는 전매 목적인 투자자라면 중도금은 하지 않는 것이 좋겠다.



가끔 분양계약한 후 난 계약금만 넣었고 중도금은 무이자 대출이라 해약금에 의한 계약해제가 되지 않느냐고 물어보시는 분들이 있는데 중도금 무이자 대출도 계약자 명의로 은행에 대출 계약을 한 것으로 시행사에서 이자를 내주고 은행에서 중도금을 주는 구조이기에 중도금이 실행된 것이다.



A씨가 이런 경우로 시행사에서 계약해제를 받아주지 않는 한 계약자인 A씨가 계약금 포기하더라도 일방적인 계약해제는 할 수가 없다.

계약해제와 계약해지
참고로 계약을 깨는 것을 두고 계약해제와 계약해지를 헷갈리시는 분들이 많은데 유효한 계약을 소멸시킨다는 의미에서는 비슷하지만 계약해제는 일시적 계약을 소급하여 소멸시키는 반면 계약해지는 계속적 계약을 장래에 대해 소멸시키는 것이다.



예를 들어 위의 경우처럼 매매계약을 깨는 것은 일시적인 계약을 소멸시켜서 아예 없던 것으로 만드는 것이기에 계약해제가 되며, 전세 계약을 한 후 1년 동안 살다가 계약을 소멸시키는 것은 계약해지가 된다.



계약해지가 되면 1년 동안 살았던 계약은 유효했던 것이고 계약해지가 된 시점부터 효력이 소멸이 된다. 



그래서 A씨의 경우에는 계약해지가 아니라 계약해제가 맞다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약 주의사항'
, '국토교통부 실거래가 공개시스템
국토교통부 실거래가 공개시스템홈페이지를 통해서 알 수 있습니다
인터넷에서 매물 검색시 가격과 함께 보아야 할 항목을 알려드립니다. 
?

1. 지하철, 버스와 같은 교통과 편의시설

2. 중심상권과의 거리

3. 아이가 있는 집이라면 어린이집, 유치원, 학교가 도보로 통학 가능한지

4. 주차장은 지상인지 지하인가

5.가구별 주차대수 비율은 얼마나 되는가


등기부등본 필수 확인 
다음으로 해당 매물의 등기부등본을 반드시 보셔야 합니다. 
부동산 거래를 할 때 수시로 등기부등본 보는 것은 아주 습관이 되셔야 해요. 정말 중요한 정보들이 있습니다. 
등기부등본은 부동산에서 발급해 달라고 요청하면 발급을 해주기도 하지만 직접 발급하는 습관을 가지세요. 

등기부등본은 집주인 동의 없이 신분증도 없이 아무나 발급이 가능합니다.  
법원의 인터넷 등기소 사이트를 통해 직접 열람도 가능하고, 전세 계약시 또한 입주 후에도  수시로 발급해서 보아야 합니다. 

이 등기부등본에는 해당 매물의 실소유자와 담보대출의 유무가 기재되어 있습니다. 또한 건물의 구조, 면적, 대지권, 소유권자, 소유권분쟁여부, 가압류, 가처분 유무, 저당권, 전세권 등이 표시가 됩니다. 
이 정보들을 반드시 확인하셔야 하는데 만약 소유권분쟁이 있거나, 가압류, 가처분이 있다면 이 매물은 거래하지 마세요. 

깡통전세 유무 확인 
두번째 등기부등본을 보면 보통은 매물에 담보대출이 껴 있는 경우가 대부분인데 깡통전세가 아닌지 인을 반드시 해보셔야 합니다. 

깡통전세란 
대출 및 보증금의 합이 집값보다 더 큰 경우를 뜻한다. 
즉 전세 기간이 다 되었을 때 집주인이 대출금을 제때 갚지 못해 전세보증금을
되돌려 받을 수 없는 상황에 놓여 있음을 의미 한다.
예를 들면 집값은 1억인데 전세금이 2억이라면 이 집주인은 남은 차액 1억으로 대출을 더해 다른 곳에 투자를 할 수 있기 때문에 세입자가 전세만료시 보증금을 돌려 받을 수 없는 위험에 처하게 되는 것입니다.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약 주의사항2'
, '이 빚을 전문용어로 "근저당권"이라고 하는데요

이 근저당권이 설정되어 있고, 향후 보증금을 돌려받을 수 없을 정도의 규모인지 살펴보아야 합니다. 

이 근저당권을 없애고 싶으면 계약시 특약에 임차인이 원하는 날짜까지 근저당권을 설정하지 않는 다는 조건을 임대차서류 특약에 남기고 실제로 이것이 이행되고 있는지 등기부등본을 수시로 열람하여 확인을 해 보아야 합니다. 

이 특약을 남길 때는 이를 어겼을 때 어떻게 보상할지 명확하게 작성하여야 합니다. 

이럼에도 불구하고 전세금반환에 대한 불안감이 있으시면 주택도시보증공사가 진행하는 보증금반환제도를 이용할 수 있습니다. 


매물 실물 영접 
다음으로 직접 매물을 보러 가야 합니다. 
매물을 실제 눈으로 확인할 때 주의사항은 절대 집이 예쁘고 깔끔하다고 덜컥 계약하면 안된다는 점입니다. 


매물을 육안으로 확인할 때 주의사항
1. 집내부의 구조가 편리하게 되어 있는가

2. 햇빛이 잘 드는가

3. 관리비가 얼마나 드는가

4.전기, 벽지 등 보수요청을 할 곳이 있는지 

5. 수도/배관/난방을 확인한다. 

6. 붙박이장이나 싱크대 등은 상태가 쓸 만한가 

7.곰팡이가 있는가?

8. 샤시나 창문 제대로 기능하는가?

이  때 제가 경험한 부동산 소장님은 집의 하자를 자세히 캐낼까봐 일부러 집을 빨리 보여주고 끝내시려는 분도 있었어요. 부동산 소장님은 보통 집주인과의 지속적인 계약을 위하여 집주인 편인 경우가 많기 때문에 쫄지 마시고 당당하게 요구사항을 이야기하셔야 합니다.

?

가계약금 넣기 전 집주인과 조건 상담 
가계약금을 넣기 전에 부동산 소장님, 집주인과 상의를 해야 합니다. 

이 때 주의사항은 

1.전세보증금이 부족한 경우 대출을 받아야 하는데 계약시에 집주인에게 대출을 받아도 되는지 미리 물어봐야 합니다. 간혹 대출을 거부하는 집주인이 있는데 이럴 경우를 대비해서 특약에 전세대출이 거절될 시 계약을 취소한다고 명시해 두어야 합니다. 


2.또한 수도, 보일러, 에어컨 등이 고장 났을 때 수리비를 누가 지불할 것인지 특약에 기재하셔야 합니다. 
?

3.집주인이 바빠서 대리인과 진행하는 경우, 위임장과 가족관계증명서를 확인해야 합니다. 되도록 등기부등본상 실소유자와 직접 거래하여야 합니다. 
대리인을 통해 진행하게 되었다면 실소유자 명의의 통장으로 바로  가계약금을 이체하는 것이 좋습니다. 


'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, '전세계약 주의사항3'
, '가계약금 입금 
 가계약금이나 잔금을 보낼 때 이체 한도가 모자를 수 있으니 미리 은행에 가서 이체 한도를 늘리셔야 합니다. 

 저는 이 가계약금이 향후 되돌려주면 계약이 자동으로  취소되는 줄 알았는데요 절대 아닙니다. 가계약금도 계약으로서 법적효력이 있고 계약 파기시 상대방에게 위자료까지 물어주어야 하기 때문에 가계약금은 신중하게 생각하셔서 입금하셔 합니다. 

 특히 부동산에서 아이들 때문에 정신 없는 주말에 전화가 와서 가계약금을 입금하라고 하는 경우에는 일단 보류하고, 차분히 생각할 수 있는 시간에 가계약금 입금을 하셔야 합니다. 그리고 계약금 입금 전에 경험이 많은 부모님과 반드시 상의를 하시고요. 



가계약금을 입금할 때는 계약자명과 가계약금 입금자명이 동일한지 확인을 해야 합니다. 특히 집주인이 오지 않고 ,부동산 소장님과 계약을 하는 실수는 하지 말아야 합니다. 


 저는 집주인이 외국에 있어서 대리인이 와서 계약을 한 적이 있는데요, 대리인이 본인의  신분증과 위임장을 가지고 오셔서 부동산에서 계약을 했어요. 대리인일 경우 이렇게 신분증과 위임증을 반드시 가지고 오시라고 하셔야 합니다. 
?

가계약금 입금 후 확정일자 바로 받기 
계약을 한 직후에는 주민센터나 온라인으로 확정일자를 받아야 합니다. 이 확정일자는 향후 내 전세금을 지키기 위해 최소한의 장치이기 때문에 꼭 받으셔야 합니다

본계약 
부동산 소장님께서 집주인과 세입자를 두고 계약서를 읽어주는데요 이 때 주의집중하셔야 합니다. 깨알같은 글씨를 총알 날라가 듯 읽으시기 때문에 집중력이 흐트러지지 않게 전날 밤에 잠을  충분히 주무시고 오셔야 하고, 저 같은 경우는 형광펜을 들고 가서 주요부분에 하이라이트를 하면 꼼꼼히 읽었습니다. 


본계약에 싸인하기 전에 또 한번 확인해야 하는 것?

뭐라구요? 등.기.부.등.본!

등기부등본을 통해 그 사이 집주인이 또 근저당권 설정을 추가로 하지 않았는지 다시 확인해보세요. 안그러면 내 소중한 전세 보증금을 날릴 수 있으니까요. 

?
이사 및 잔금납입 
이사날이 되면 잔금을 치릅니다. 
잔금을 치루고, 이사짐 풀지 마시고 이 때 먼저 해야 하는 것은 주민센터에 가셔서 전입신고를 하셔야 합니다. 

?

전입신고란 
거주지를 이동한 때에 새로운 거주지에 전입한 사실을 거주지 관할 기관에 신고하는 것
전입신고를 해 두셔야 혹시나 이 집에 경매에 넘어가게 되더라도 내 보증금을 우선적으로 받을 수 가 있게 됩니다. 

 마지막으로 부동산 소장님께 중개수수료를 납입하게 됩니다. 중개수수료는 현금영수증 의무발행이기 때문에 부동산 소장님이 필수로 파일에 넣어 주실 거에요.'
, SYSDATE, 1, 1);


INSERT INTO TBL_INFO_BOARD A (A.POST_NO, A.POST_TITLE, A.POST_CONTENT, A.CREATION_DATE, A.CATEGORY_NO, A.USER_NO)
VALUES (SEQ_INFO_POST_NO.NEXTVAL, ' 전세자금대출 진행절차와 유의사항'
, '서민 주거안정의 가장 일반적 방법인 전세시장...
오늘은 "전세자금대출 진행절차와 유의사항"에 대해서 설명 드리도록 하겠습니다.

*전세자금 대출의 일반적인 기준
  1) 만20세 이상
  2) 전세입주예정자 또는 전세거주자
  3) 전세자금대출에는 중소기업 취업청년 대출, 버팀목대출, 일반 시중은행의 대출이 있다.

*이자율 비교
  중소기업 청년대출(연1.2%), 버팀목 대출(연2.3~2.9%), 일반시중은행 대출(2.9~3.5%)

*전세자금대출 진행 절차
  1) 부동산을 통해 전세자금대출이 가능한 집을 구한다.
  2) 임대차 계약서를 작성한다.(계약금 5%,확정일자)
  3) 은행 방문 후 대출 상담을 한다.
  4) 은행에서 집주인에게 연락해서 임대차 계약 사실 을 확인 한다.
  5) 보증기관에서 보증서를 발급 받는다.
  6) 서류를 제출하고 대출 신청한다.
  7) 대출 승인 후 대출 금은 집주인 통장으로 직접 송금된다.
  8) 전세계약 만료시 집주인이 은행에 직접 대출금을 상환한다.


전세자금대출 진행절차와 유의사항


첫번째, 집주인(임대인)의 동의를 받아야 한다.
1) 대출 진행 시 집주인의 동의가 필수
2) 처음부터 부동산에 대출 가능여부를 확인한다.
3) 잔금일 전세자금 대출은 집주인 통장으로 직접 입금된다.
4) 계약 만료 시 대출금을 집주인이 직접 금융기관에 반환해야 한다.

두번째, 전세 계약과 확정일자는 같은 날 진행한다.
1) 확정일자를 받아서 전세보증금을 안전하게 지킨다.
2) 은행 제출시 임대차 계약서에 확정일자가 찍혀 있어야 한다.
3) 전입신고를 하지 않아도 확정일자를 받을 수 있다. 
   (확정일자 : 전세계약서 지참 후 해당 주민센터로 가서 확정일자 새겨진 네모난 도장을 받을 수 있다.)
   (내 전세보증금을 지켜주는 가장 중요한 보호막 역할!!)
   (주의 ! : 이사 전에 전입신고를 하면 현재 살고 있는 집의 보증금을 보호 받을 수 없다.)

세번째. 전세자금대출 서류
1) 공통 : 임대차계약서(계약금5%, 확정일자), 집주인 통장사본, 등기부등본, 주민등록등(초)본, 가족관계증명서, 신분증
2) 급여소득자 : 재직증명서, 소득증명서
3) 자영업자 : 사업자등록증, 소득증명서


전세자금 대출은 전세 계약할 집의 건축물대장상 용도가 "주택" 이어야 하고, 위반건축물인 경우 대출이 이루어지지 않습니다.
계약 전 건축물 대장을 꼭 확인 하시고 만약 전세자금 대출이 이루어지지 않을 때를 대비해서
계약금을 반환 받는다는 특약을 임대차 계약서에 꼭 명기하시기 바랍니다.
아는만큼 손해를 보지않는 세상입니다
내 제산은 내가 꼭 지켜야 겠죠?'
, SYSDATE, 1, 1);
